### ISSUE TITLE
Issue with second yield in generator on a similarly named loop variable

### ISSUE THREAD

**Issue by eranbrodet** [tmr232/gengen#4] opened 2022-08-09 15:43 UTC
Taking the demo code example from the documentation and modifying it slightly to have another loop that yields different values after the first loop, using a loop variable with the same name in both loops:
```
func Range(stop int) gengen.Generator[int] {
	for i := 0; i < stop; i++ {
		gengen.Yield(i)
	}
	
	for i := stop; i >= 0; i-- {
		gengen.Yield(i)
	}
	return nil
}

func main() {
	numberRange := Range(10)
	for numberRange.Next() {
		fmt.Println(numberRange.Value())
    }
	if numberRange.Error() != nil {
		panic(numberRange.Error())
    }
}
```
The expected output is:
```
0
1
2
3
4
5
6
7
8
9
10
9
8
7
6
5
4
3
2
1
0
```
But the actual result is:
```
0
1
2
3
4
5
6
7
8
9
10
10
10
10
10
10
10
10
10
10
10
```

**Comment by tmr232** [comment] 2022-08-09 19:55
Thanks!

Found the issue.
Since we move all variables out of scope - we need to rename when there are conflicts.
This part works.

The issue is at https://github.com/tmr232/gengen/blob/ce81c50214e9f9a7c5cdc546b5179a80504e0439/cmd/gengen/wizard.go#L319 - when handling the yielded expression.
Instead of analyzing and formatting it properly (and renaming the variables it uses) the code just prints it as-is.
So if you look the the resulting generated code, we get:

```go
			i1 = stop
		__Head2:
			if i1 >= 0 {
				goto __Body2
			} else {
				goto __After2
			}
		__Body2:

			__next = 2
			return __withValue(i)

		__Next2:

			i1--
			goto __Head2
		__After2:
```

We generate the loop correctly, but yield the wrong variable.

**Comment by tmr232** [comment] 2022-08-10 07:41
Fixing this requires using `wiz.convertAst()` instead of `format.Node`, but doing so triggers other issues as some AST nodes are not fully implemented in `convertAst` yet.

**Closed as completed** 2022-08-13 08:35 UTC
